#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
if (length(args)<=1){
    write('To Run: Rscript convert_srp_gse_to_srp.R <gse_id1> <gse_id2>', stderr())
    quit(status=1)
}
suppressMessages(library(SRAdb))
suppressMessages(library(DBI))
suppressMessages(library(GEOmetadb))
SRAsqlfile <- 'SRAmetadb.sqlite'
GEOsqlfile <- 'GEOmetadb.sqlite'
if(!file.exists(SRAsqlfile)) SRAsqlfile <<- getSRAdbFile()
if(!file.exists(GEOsqlfile)) GEOsqlfile <<- getSQLiteFile()

input_list <- args
sra_con <- dbConnect(SQLite(), SRAsqlfile)
geo_con <- dbConnect(SQLite(), GEOsqlfile)

get_SRP_from_GSE <- function(gse){
    if (grepl('SRP', gse)){
        return (gse)
    }
    results <- as.list(dbGetQuery(geo_con, paste0("SELECT * FROM gse WHERE gse = '", gse, "'")))
    supplementary_file <- strsplit(results$supplementary_file, ';')[[1]]
    srp_match <- grep('SRP', supplementary_file, value=TRUE)
    return (sapply(strsplit(srp_match, '/'), tail, 1))

}

for (element in input_list) {
    cat(get_SRP_from_GSE(element))
    cat('\n')
}
